-- 최초 스키마 (회원 + 계정)
-- db 수정 사항이 생기면 v2, v3, ... 등으로 파일을 만들어서 버전 관리함

CREATE TABLE users (
    id                 INTEGER      GENERATED BY DEFAULT AS IDENTITY,

    nickname           VARCHAR(20)  NOT NULL,
    apt_name           VARCHAR(100) NOT NULL,
    dong               VARCHAR(20),
    ho                 VARCHAR(20),

    role               VARCHAR(20)  NOT NULL,
    status             VARCHAR(20)  NOT NULL,

    withdrawn_at       TIMESTAMP(6),
    withdrawal_reason  VARCHAR(255),

    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_nickname UNIQUE (nickname),

    -- @Enumerated(EnumType.STRING) 이라 문자열로 저장됨
    -- 이름이 바뀌거나 오타가 들어가면 DB 가 거부하도록 값을 제한함
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'WITHDRAWN'))
);

CREATE TABLE accounts (
    id                  INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    user_id             INTEGER      NOT NULL,

    email               VARCHAR(100) NOT NULL,
    password            VARCHAR(83),

    refresh_token_hash  VARCHAR(64),
    expiry_date         TIMESTAMP(6),

    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6) NOT NULL,

    CONSTRAINT pk_accounts PRIMARY KEY (id),
    CONSTRAINT uk_accounts_email UNIQUE (email),
    CONSTRAINT uk_accounts_user_id UNIQUE (user_id),
    CONSTRAINT uk_accounts_refresh_token_hash UNIQUE (refresh_token_hash),
    CONSTRAINT fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);
