-- 리프레시 토큰을 계정 테이블에서 떼어 별도 테이블로 옮김
--
-- 전에는 accounts 에 한 칸(refresh_token_hash)만 있어서 기기 하나만 로그인을 유지할 수 있었음.
--   1) 폰에서 로그인 -> 토큰 A 저장
--   2) PC 에서 로그인 -> 토큰 B 로 덮어씀 (A 무효)
--   3) 폰이 A 로 재발급 시도 -> 해시 불일치 -> 재사용으로 보고 전체 차단
--   => "PC 에서 로그인했더니 폰이 로그아웃됨"
--
-- 이제 기기마다 한 행을 쓰므로 여러 기기에서 동시에 로그인할 수 있음.
-- 재사용 감지는 그대로 동작함(해시에 해당하는 행이 없으면 그 계정의 토큰을 전부 지움)

CREATE TABLE refresh_tokens (
    id          INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    account_id  INTEGER      NOT NULL,

    -- 토큰 원문이 아니라 SHA-256 16진수 64자를 담음
    -- 원문을 담으면 DB 가 유출됐을 때 그대로 로그인에 쓸 수 있는 자격 증명이 되기 때문임
    token_hash  VARCHAR(64)  NOT NULL,
    expires_at  TIMESTAMP(6) NOT NULL,

    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,

    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),

    -- 하나의 토큰이 두 계정을 인증하는 상태를 DB 차원에서 막음
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),

    -- 계정이 지워지면 그 계정의 토큰도 함께 지워지도록 함
    CONSTRAINT fk_refresh_tokens_account_id FOREIGN KEY (account_id)
        REFERENCES accounts (id) ON DELETE CASCADE
);

-- 로그아웃·탈퇴에서 계정 단위로 지우고, 기기 수를 셀 때도 이 칼럼으로 찾음
CREATE INDEX ix_refresh_tokens_account_id ON refresh_tokens (account_id);

-- accounts 에 있던 옛 칸을 치움
-- 운영 DB 에는 아직 회원이 없어서 옮길 데이터가 없음.
-- 회원이 있는 상태에서 이 마이그레이션을 돌리면 로그인만 다시 하면 됨(비밀번호는 그대로임)
ALTER TABLE accounts DROP CONSTRAINT uk_accounts_refresh_token_hash;
ALTER TABLE accounts DROP COLUMN refresh_token_hash;
ALTER TABLE accounts DROP COLUMN expiry_date;
