-- 개인정보 파기 기록
--
-- 약관(개인정보 수집·이용 동의)에 "회원 탈퇴 후 30일까지 보유하고 그 뒤 파기한다" 고 적어 두었음.
-- 전에는 탈퇴가 status 를 WITHDRAWN 으로 바꾸는 것뿐이어서 이메일·비밀번호 해시·단지 정보가
-- 계속 남아 있었음. 적어 둔 것과 실제 동작이 달랐던 것임
--
-- 이제 WithdrawnDataPurgeService 가 기한이 지난 회원의 users/accounts 행을 지우고,
-- 지웠다는 사실만 이 표에 남김
--
-- 이 표에 개인을 알아볼 수 있는 값은 담지 않음.
-- 지워진 회원의 번호와 시각만 남기므로, 표만 봐서는 누구였는지 알 수 없음.
-- (그 번호로 되짚을 수 있는 행이 이미 없음)
CREATE TABLE data_erasure_logs (
    id           INTEGER      GENERATED BY DEFAULT AS IDENTITY,

    -- 지워진 users.id. 외래키를 걸지 않음. 참조 대상이 이미 사라졌기 때문임
    user_id      INTEGER      NOT NULL,

    withdrawn_at TIMESTAMP(6) NOT NULL,
    erased_at    TIMESTAMP(6) NOT NULL,

    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,

    CONSTRAINT pk_data_erasure_logs PRIMARY KEY (id),

    -- 같은 회원을 두 번 지운 것으로 기록되는 일을 막음
    CONSTRAINT uk_data_erasure_logs_user_id UNIQUE (user_id)
);
