-- 약관 동의 기록
--
-- 왜 필요한가: 화면에는 약관 세 건의 동의 체크박스가 있는데, 동의했다는 사실이 어디에도
-- 남지 않았음. 체크를 받아 다음 단계로 넘기는 것이 전부였고 가입 요청에도 담기지 않았음
--
-- 개인정보 보호법 제22조는 동의를 각각 알리고 받으라고 하고, 동의를 받았다는 사실의
-- 입증 책임은 사업자에게 있음. 기록이 없으면 분쟁에서 증명할 방법이 없음
--
-- 그리고 프런트의 "다음" 버튼 비활성화는 막는 장치가 아님. 개발자 도구로 지울 수 있고
-- API 를 직접 부르면 아예 거치지 않음. 그래서 서버가 필수 약관 동의를 다시 확인함
--
-- 동의한 약관의 "판"도 함께 남김. 약관을 개정하면 그 뒤에 가입한 사람과 이전에 가입한 사람이
-- 서로 다른 내용에 동의한 것이므로, 어느 판에 동의했는지가 기록의 핵심임
CREATE TABLE terms_agreements (
    id            INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    user_id       INTEGER      NOT NULL,

    -- 약관 종류. 프런트 constants/terms.ts 의 TermsKey 와 같은 값임
    --   service   : 서비스 이용약관 (필수)
    --   privacy   : 개인정보 수집·이용 동의 (필수)
    --   marketing : 마케팅 정보 수신 동의 (선택)
    terms_key     VARCHAR(20)  NOT NULL,

    -- 동의한 약관의 판. 시행일자를 그대로 씀 (예: "시행일자 2026년 8월")
    terms_version VARCHAR(40)  NOT NULL,

    -- 선택 약관은 동의하지 않은 것도 기록함
    -- "동의 안 함" 을 받았다는 사실 자체가 기록되어야 마케팅 발송 여부를 증명할 수 있음
    agreed        BOOLEAN      NOT NULL,
    agreed_at     TIMESTAMP(6) NOT NULL,

    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,

    CONSTRAINT pk_terms_agreements PRIMARY KEY (id),

    -- 한 회원이 같은 약관에 두 줄을 남기는 것을 막음
    -- 재동의(약관 개정 뒤 다시 받는 경우)를 따로 쌓아야 하면 이 제약을
    -- (user_id, terms_key, terms_version) 으로 넓혀야 함
    CONSTRAINT uk_terms_agreements_user_key UNIQUE (user_id, terms_key),

    -- 회원이 지워지면 동의 기록도 함께 지워지도록 함
    -- 개인정보 파기 기한(탈퇴 후 30일)에 이 기록도 같이 사라지는 것이 약관과 맞음.
    -- 파기했다는 사실은 data_erasure_logs 가 남김
    CONSTRAINT fk_terms_agreements_user_id FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

-- 회원 단위로 찾고 지우므로 이 칼럼으로 색인함
CREATE INDEX ix_terms_agreements_user_id ON terms_agreements (user_id);

COMMENT ON TABLE terms_agreements IS '약관 동의 기록임. 동의 사실의 입증 책임이 사업자에게 있어 반드시 남김';
COMMENT ON COLUMN terms_agreements.terms_version IS '동의한 약관의 시행일자임. 개정 전 판에 동의한 회원을 구분하려고 남김';
COMMENT ON COLUMN terms_agreements.agreed IS '선택 약관의 거부도 기록함. 거부를 받았다는 사실도 증명 대상임';
