name: PR Title Check

on:
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write

jobs:
  title:
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          types: |
            feat
            fix
            chore
            test
            refactor
            docs
            style
            perf
            deploy
